name: flutter_launcher_icons
description: A package which simplifies the task of updating your Flutter app's launcher icon.
version: 1.0.0+1
maintainer: Mark O'Sullivan (@MarkOSullivan94)
homepage: https://github.com/fluttercommunity/flutter_launcher_icons
authors:
  - Flutter Community <community@flutter.zone>
  - Franz Silva <franzsilva@gmail.com>
  - Mark O'Sullivan <mos182@hotmail.co.uk>
  - Dorofeev Iurii <otopba@inbox.ru>

dependencies:
  args: ^2.3.0
  image: ^3.1.3
  yaml: ^3.1.0

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  test: "^1.6.3"
